/** Auto-generated by scripts/sync-resources-from-github.mjs */
import type { ResourcePages } from './resources-catalog.mts'

export const RESOURCE_PAGES: Record<string, ResourcePages> = {
  "bodybag": {
    "configuration": true,
    "commonErrors": true
  },
  "burger-shop": {
    "configuration": true,
    "commonErrors": true
  },
  "carwipe": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": true
    },
    "commonErrors": true
  },
  "chopshop": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": true
    },
    "commonErrors": true
  },
  "duty-system": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": true
    },
    "commonErrors": true
  },
  "fraud-v1": {
    "configuration": true,
    "commonErrors": true
  },
  "fraud-v2": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": false
    },
    "commonErrors": true
  },
  "gun-jamming": {
    "configuration": true,
    "commonErrors": true
  },
  "icebox": {
    "configuration": true,
    "commonErrors": true
  },
  "lashes-saloon": {
    "configuration": true,
    "commonErrors": true
  },
  "loading-screen": {
    "configuration": true,
    "commonErrors": true
  },
  "nails-saloon": {
    "configuration": true,
    "commonErrors": true
  },
  "npc-medic": {
    "configuration": true,
    "commonErrors": true
  },
  "notify": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": true
    },
    "questions": true,
    "commonErrors": false
  },
  "outfitbag": {
    "configuration": true,
    "commonErrors": true
  },
  "pizza-shop": {
    "configuration": true,
    "commonErrors": true
  },
  "items-placeables": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": false
    },
    "commonErrors": true
  },
  "portable-parking": {
    "configuration": true,
    "commonErrors": true
  },
  "safezone-creator": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": true
    },
    "functions": {
      "client": true,
      "server": true
    },
    "commonErrors": true
  },
  "shoes-robbery": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": false
    },
    "commonErrors": true
  },
  "skitz-shoes-store": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": false
    },
    "commonErrors": true
  },
  "smoking": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": false
    },
    "commonErrors": true
  },
  "starter-pack": {
    "configuration": true,
    "commonErrors": true
  },
  "switch": {
    "configuration": true,
    "commonErrors": true
  },
  "tranquilizer": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": true
    },
    "commonErrors": true
  },
  "trap-phone-v1": {
    "configuration": true,
    "commonErrors": true
  },
  "trap-phone-v2": {
    "exports": {
      "client": false,
      "server": true
    },
    "commonErrors": true
  },
  "useable-foods": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": true
    },
    "commonErrors": true
  },
  "weave-wear": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": false
    },
    "commonErrors": true
  },
  "white-widow": {
    "configuration": true,
    "exports": {
      "client": true,
      "server": false
    },
    "commonErrors": true
  },
  "wigs-bundle": {
    "configuration": true,
    "commonErrors": true
  },
  "automatic-pistol-pack": {
    "commonErrors": true
  },
  "weapon-pack-v1": {
    "commonErrors": true
  }
}
